
package knjiznicasoap.client;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "KnjigomatiSoapService", targetNamespace = "http://soap.knjiznica.javaee.feri.um.si/", wsdlLocation = "http://localhost:8080/webapp/KnjigomatiSoap?wsdl")
public class KnjigomatiSoapService
    extends Service
{

    private final static URL KNJIGOMATISOAPSERVICE_WSDL_LOCATION;
    private final static WebServiceException KNJIGOMATISOAPSERVICE_EXCEPTION;
    private final static QName KNJIGOMATISOAPSERVICE_QNAME = new QName("http://soap.knjiznica.javaee.feri.um.si/", "KnjigomatiSoapService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/webapp/KnjigomatiSoap?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        KNJIGOMATISOAPSERVICE_WSDL_LOCATION = url;
        KNJIGOMATISOAPSERVICE_EXCEPTION = e;
    }

    public KnjigomatiSoapService() {
        super(__getWsdlLocation(), KNJIGOMATISOAPSERVICE_QNAME);
    }

    public KnjigomatiSoapService(WebServiceFeature... features) {
        super(__getWsdlLocation(), KNJIGOMATISOAPSERVICE_QNAME, features);
    }

    public KnjigomatiSoapService(URL wsdlLocation) {
        super(wsdlLocation, KNJIGOMATISOAPSERVICE_QNAME);
    }

    public KnjigomatiSoapService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, KNJIGOMATISOAPSERVICE_QNAME, features);
    }

    public KnjigomatiSoapService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public KnjigomatiSoapService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns KnjigomatiSoap
     */
    @WebEndpoint(name = "KnjigomatiSoapPort")
    public KnjigomatiSoap getKnjigomatiSoapPort() {
        return super.getPort(new QName("http://soap.knjiznica.javaee.feri.um.si/", "KnjigomatiSoapPort"), KnjigomatiSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns KnjigomatiSoap
     */
    @WebEndpoint(name = "KnjigomatiSoapPort")
    public KnjigomatiSoap getKnjigomatiSoapPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://soap.knjiznica.javaee.feri.um.si/", "KnjigomatiSoapPort"), KnjigomatiSoap.class, features);
    }

    private static URL __getWsdlLocation() {
        if (KNJIGOMATISOAPSERVICE_EXCEPTION!= null) {
            throw KNJIGOMATISOAPSERVICE_EXCEPTION;
        }
        return KNJIGOMATISOAPSERVICE_WSDL_LOCATION;
    }

}
