
package knjiznicasoap.client;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "KnjigomatiSoap", targetNamespace = "http://soap.knjiznica.javaee.feri.um.si/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface KnjigomatiSoap {


    /**
     * 
     * @return
     *     returns java.util.List<knjiznicasoap.client.Knjigomat>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "vrniVse", targetNamespace = "http://soap.knjiznica.javaee.feri.um.si/", className = "knjiznicasoap.client.VrniVse")
    @ResponseWrapper(localName = "vrniVseResponse", targetNamespace = "http://soap.knjiznica.javaee.feri.um.si/", className = "knjiznicasoap.client.VrniVseResponse")
    public List<Knjigomat> vrniVse();

    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "shrani", targetNamespace = "http://soap.knjiznica.javaee.feri.um.si/", className = "knjiznicasoap.client.Shrani")
    @ResponseWrapper(localName = "shraniResponse", targetNamespace = "http://soap.knjiznica.javaee.feri.um.si/", className = "knjiznicasoap.client.ShraniResponse")
    public void shrani(
        @WebParam(name = "arg0", targetNamespace = "")
        Knjigomat arg0);

}
